script:
  - cargo build --verbose --release
  - cargo test --verbose
language: rust
rust:
  - stable
deploy:
  provider: releases
  token:
    secure: "ht/CYzJNTT+wQPbuAY/FUBAU6SwUsnZJIVb0xFtwi06T/61w55Fn28uDuHIAlgq/lPqdkQoYrs1kpMCmVUvGfOBq3oMUvnSzbSCKk9yZ7dbD/ZYaTlL7lwc7a3v1nn2GI+ocfHQbvX2qfGkx97t1q3d8L7HylNp7fNlptu4KCSKnXUSGwcrUoTs/TOjBjFhfO8paPmLBOdG6Gpb7opOhCZetr8YUWprfXOOwpr0z7OWAA+5iiAytA9xhz+uKbtPutylI+oCJMwZN43WuJhXpCjlMyAjQQrPCdQ1fWrNb2Bhxp3/ML0E1tqnA43uf1zcXWG+hxBb3dfnaM0eHax0q8hK0s4Q4hwFeLaYBm5LibtmFSf511LGMIHkO09Lk+qyEZntZ6P2LudiBZD4tnWxUhDvpuQ8FJbFunlm4Af2mZhbZNfi/4S/SsFEzk8ZEgY2vtD7K9/G2P3JUEVUd2NwgjHlACF8IZA2rQWxl5/QHWbHTe3+K39ERk5vLBce0NzCUs7pzRobOdFy3fXhjrCZUwe0YDd8Cg8X4cGKxALrxFbFgX6z0kbCaDNk6U77vKRfvBCGaHPg7gxJMqt/3bgMVE0AsVvvovMEetQaEzAPt4MBn6QXoExx0ad64KaUC/ZCkZkjhxY+sG3V3Thofg/C8neof5h8V+b2QiEC1Ed+46FA="
  file: "./target/release/notes_rust"
  skip_cleanup: true
  draft: true
  edge: true
  on:
    branch: main
