language: rust
rust:
  - stable
deploy:
  provider: releases
  token: "wAtKrYiQzJU7y4dev8IjO6Xpf2x6IUl5vC2TQeFa989qujv194XZE2BeG4Q9YYmYK2k8hfBHTMqVLAwi8/kicUtX2w5xGIV3/VxinlRGsVp75Bogqi4h8H+2PoU7c/CR4rObflIF7Hhqr34TCiFiQ5udFVjnEufKAKZL+HiGSmmsFTgIXOXFNWuL9hA5qCu0veckdEaFyi0DsaIGKTD81hZijeWBCnrbCsaQ6i1v2tpDZPCP1Kg5Vp33cFwCgHw+RGiFAT0ICMrSQ7YhGGkmLfwTJW7oCQKMHYQwgHpv51KheCZydMBPg5D6Ia6K7/eHuLZF6VJKRyl/45rwxUiqh9Csj0rEU/rX3mKjydcY2+y6dely3n2VhOHNUtxuRoX+9B2NhXxwXKLbLvKMINg3oyzLffNGsz2OYeUw67a3UuGVGQbPhNSegF2IcZ+f3IRs3y5WoRND1VmWs7W4qa2Q3XTps/50jHDZ5UJ/lpPOhuMlTpgWBdXY8GLtFZxcB/wS70Z1yFZqhotGFWOMxnkqrm+Lo6DBiFS9OAG6o9XCJyUPKQFdOxOmEkdRHKivNimeIKxm1gQzTX9JGYaGm0Q87JeOqVDjbGMxChADg3CHEUgTF86igor/gquINI2LFMyCbc+xiUxvcBfsDNalPBGDapdndIIaKGdqXIBhuRDZiks="
  file: "./target/release/notes_rust"
  skip_cleanup: true
  draft: true
  edge: true
  on:
    branch: main
